/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author edgar_000
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Tablero8 = new javax.swing.JButton();
        Btn_Tablero9 = new javax.swing.JButton();
        Btn_Tablero10 = new javax.swing.JButton();
        Btn_Tablero11 = new javax.swing.JButton();
        Btn_Tablero12 = new javax.swing.JButton();
        Btn_Tablero7 = new javax.swing.JButton();
        Btn_Tablero2 = new javax.swing.JButton();
        Btn_Tablero3 = new javax.swing.JButton();
        Btn_Tablero4 = new javax.swing.JButton();
        Btn_Tablero5 = new javax.swing.JButton();
        Btn_Tablero6 = new javax.swing.JButton();
        Btn_Tablero1 = new javax.swing.JButton();
        Btn_Tablero20 = new javax.swing.JButton();
        Btn_Tablero21 = new javax.swing.JButton();
        Btn_Tablero22 = new javax.swing.JButton();
        Btn_Tablero23 = new javax.swing.JButton();
        Btn_Tablero24 = new javax.swing.JButton();
        Btn_Tablero19 = new javax.swing.JButton();
        Btn_Tablero14 = new javax.swing.JButton();
        Btn_Tablero15 = new javax.swing.JButton();
        Btn_Tablero16 = new javax.swing.JButton();
        Btn_Tablero17 = new javax.swing.JButton();
        Btn_Tablero18 = new javax.swing.JButton();
        Btn_Tablero13 = new javax.swing.JButton();
        Btn_Tablero32 = new javax.swing.JButton();
        Btn_Tablero33 = new javax.swing.JButton();
        Btn_Tablero34 = new javax.swing.JButton();
        Btn_Tablero35 = new javax.swing.JButton();
        Btn_Tablero36 = new javax.swing.JButton();
        Btn_Tablero31 = new javax.swing.JButton();
        Btn_Tablero26 = new javax.swing.JButton();
        Btn_Tablero27 = new javax.swing.JButton();
        Btn_Tablero28 = new javax.swing.JButton();
        Btn_Tablero29 = new javax.swing.JButton();
        Btn_Tablero30 = new javax.swing.JButton();
        Btn_Tablero25 = new javax.swing.JButton();
        L_Turno = new javax.swing.JLabel();
        Btn_Turno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Btn_Tablero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tablero8ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Tablero8);
        Btn_Tablero8.setBounds(100, 360, 80, 70);
        getContentPane().add(Btn_Tablero9);
        Btn_Tablero9.setBounds(190, 360, 80, 70);
        getContentPane().add(Btn_Tablero10);
        Btn_Tablero10.setBounds(280, 360, 80, 70);

        Btn_Tablero11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tablero11ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Tablero11);
        Btn_Tablero11.setBounds(370, 360, 80, 70);
        getContentPane().add(Btn_Tablero12);
        Btn_Tablero12.setBounds(460, 360, 80, 70);
        getContentPane().add(Btn_Tablero7);
        Btn_Tablero7.setBounds(10, 360, 80, 70);
        getContentPane().add(Btn_Tablero2);
        Btn_Tablero2.setBounds(100, 440, 80, 70);
        getContentPane().add(Btn_Tablero3);
        Btn_Tablero3.setBounds(190, 440, 80, 70);
        getContentPane().add(Btn_Tablero4);
        Btn_Tablero4.setBounds(280, 440, 80, 70);
        getContentPane().add(Btn_Tablero5);
        Btn_Tablero5.setBounds(370, 440, 80, 70);
        getContentPane().add(Btn_Tablero6);
        Btn_Tablero6.setBounds(460, 440, 80, 70);
        getContentPane().add(Btn_Tablero1);
        Btn_Tablero1.setBounds(10, 440, 80, 70);
        getContentPane().add(Btn_Tablero20);
        Btn_Tablero20.setBounds(100, 200, 80, 70);
        getContentPane().add(Btn_Tablero21);
        Btn_Tablero21.setBounds(190, 200, 80, 70);
        getContentPane().add(Btn_Tablero22);
        Btn_Tablero22.setBounds(280, 200, 80, 70);
        getContentPane().add(Btn_Tablero23);
        Btn_Tablero23.setBounds(370, 200, 80, 70);
        getContentPane().add(Btn_Tablero24);
        Btn_Tablero24.setBounds(460, 200, 80, 70);
        getContentPane().add(Btn_Tablero19);
        Btn_Tablero19.setBounds(10, 200, 80, 70);
        getContentPane().add(Btn_Tablero14);
        Btn_Tablero14.setBounds(100, 280, 80, 70);
        getContentPane().add(Btn_Tablero15);
        Btn_Tablero15.setBounds(190, 280, 80, 70);
        getContentPane().add(Btn_Tablero16);
        Btn_Tablero16.setBounds(280, 280, 80, 70);

        Btn_Tablero17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tablero17ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Tablero17);
        Btn_Tablero17.setBounds(370, 280, 80, 70);
        getContentPane().add(Btn_Tablero18);
        Btn_Tablero18.setBounds(460, 280, 80, 70);

        Btn_Tablero13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tablero13ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Tablero13);
        Btn_Tablero13.setBounds(10, 280, 80, 70);
        getContentPane().add(Btn_Tablero32);
        Btn_Tablero32.setBounds(100, 40, 80, 70);
        getContentPane().add(Btn_Tablero33);
        Btn_Tablero33.setBounds(190, 40, 80, 70);

        Btn_Tablero34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tablero34ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Tablero34);
        Btn_Tablero34.setBounds(280, 40, 80, 70);
        getContentPane().add(Btn_Tablero35);
        Btn_Tablero35.setBounds(370, 40, 80, 70);
        getContentPane().add(Btn_Tablero36);
        Btn_Tablero36.setBounds(460, 40, 80, 70);
        getContentPane().add(Btn_Tablero31);
        Btn_Tablero31.setBounds(10, 40, 80, 70);
        getContentPane().add(Btn_Tablero26);
        Btn_Tablero26.setBounds(100, 120, 80, 70);
        getContentPane().add(Btn_Tablero27);
        Btn_Tablero27.setBounds(190, 120, 80, 70);
        getContentPane().add(Btn_Tablero28);
        Btn_Tablero28.setBounds(280, 120, 80, 70);
        getContentPane().add(Btn_Tablero29);
        Btn_Tablero29.setBounds(370, 120, 80, 70);
        getContentPane().add(Btn_Tablero30);
        Btn_Tablero30.setBounds(460, 120, 80, 70);
        getContentPane().add(Btn_Tablero25);
        Btn_Tablero25.setBounds(10, 120, 80, 70);

        L_Turno.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        L_Turno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Turno.setText("Lobo");
        L_Turno.setToolTipText("");
        getContentPane().add(L_Turno);
        L_Turno.setBounds(560, 50, 130, 30);

        Btn_Turno.setText("Turn!");
        Btn_Turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TurnoActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Turno);
        Btn_Turno.setBounds(590, 80, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Tablero34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tablero34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Tablero34ActionPerformed

    private void Btn_Tablero11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tablero11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Tablero11ActionPerformed

    private void Btn_Tablero17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tablero17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Tablero17ActionPerformed

    private void Btn_Tablero13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tablero13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Tablero13ActionPerformed

    private void Btn_TurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TurnoActionPerformed
        // TODO add your handling code here:
        int turno= (int) (Math.random()*6+1);
         L_Turno.setText(""+turno);
         
        if (turno==1)
             L_Turno.setText("Lobo");
        if (turno==2)
            L_Turno.setText("Vampiro");
        if (turno==3)
            L_Turno.setText("Muerte");
        if (turno==4)
            L_Turno.setText("Muerte B");
        if (turno==5)
            L_Turno.setText("Vampiro B");
         if (turno==6)
            L_Turno.setText("Lobo B");
    
      
    }//GEN-LAST:event_Btn_TurnoActionPerformed

    private void Btn_Tablero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tablero8ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Btn_Tablero8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Tablero1;
    private javax.swing.JButton Btn_Tablero10;
    private javax.swing.JButton Btn_Tablero11;
    private javax.swing.JButton Btn_Tablero12;
    private javax.swing.JButton Btn_Tablero13;
    private javax.swing.JButton Btn_Tablero14;
    private javax.swing.JButton Btn_Tablero15;
    private javax.swing.JButton Btn_Tablero16;
    private javax.swing.JButton Btn_Tablero17;
    private javax.swing.JButton Btn_Tablero18;
    private javax.swing.JButton Btn_Tablero19;
    private javax.swing.JButton Btn_Tablero2;
    private javax.swing.JButton Btn_Tablero20;
    private javax.swing.JButton Btn_Tablero21;
    private javax.swing.JButton Btn_Tablero22;
    private javax.swing.JButton Btn_Tablero23;
    private javax.swing.JButton Btn_Tablero24;
    private javax.swing.JButton Btn_Tablero25;
    private javax.swing.JButton Btn_Tablero26;
    private javax.swing.JButton Btn_Tablero27;
    private javax.swing.JButton Btn_Tablero28;
    private javax.swing.JButton Btn_Tablero29;
    private javax.swing.JButton Btn_Tablero3;
    private javax.swing.JButton Btn_Tablero30;
    private javax.swing.JButton Btn_Tablero31;
    private javax.swing.JButton Btn_Tablero32;
    private javax.swing.JButton Btn_Tablero33;
    private javax.swing.JButton Btn_Tablero34;
    private javax.swing.JButton Btn_Tablero35;
    private javax.swing.JButton Btn_Tablero36;
    private javax.swing.JButton Btn_Tablero4;
    private javax.swing.JButton Btn_Tablero5;
    private javax.swing.JButton Btn_Tablero6;
    private javax.swing.JButton Btn_Tablero7;
    private javax.swing.JButton Btn_Tablero8;
    private javax.swing.JButton Btn_Tablero9;
    private javax.swing.JButton Btn_Turno;
    private javax.swing.JLabel L_Turno;
    // End of variables declaration//GEN-END:variables
}
